# Generated by Django 3.1.3 on 2021-01-08 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semrush',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('keyword', models.CharField(blank=True, max_length=255, null=True)),
                ('seed_keyword', models.CharField(blank=True, max_length=255, null=True)),
                ('tags', models.CharField(blank=True, max_length=255, null=True)),
                ('volume', models.IntegerField(blank=True, max_length=255, null=True)),
                ('keyword_difficulty', models.CharField(blank=True, max_length=255, null=True)),
                ('ccp', models.CharField(blank=True, max_length=255, null=True)),
                ('competitive_density', models.CharField(blank=True, max_length=255, null=True)),
                ('number_of_results', models.CharField(blank=True, max_length=255, null=True)),
                ('serp_Features', models.TextField(blank=True, null=True)),
                ('trend', models.CharField(blank=True, max_length=255, null=True)),
                ('click_potential', models.CharField(blank=True, max_length=255, null=True)),
                ('competitors', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
