# Generated by Django 3.1.3 on 2021-01-08 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0003_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='address',
        ),
    ]
