# Generated by Django 3.1.3 on 2021-01-08 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0004_remove_employee_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[(0, 'Male'), (1, 'Female')], max_length=10),
        ),
    ]
