# Generated by Django 3.1.3 on 2021-01-27 07:14

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0007_auto_20210120_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semrush',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 27, 7, 14, 38, 513540, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='serpdatalink',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 27, 7, 14, 38, 513540, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='SerpContentDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2021, 1, 27, 7, 14, 38, 513540, tzinfo=utc))),
                ('keyword', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='serp_semrush_link', to='newsApp.semrush')),
                ('serp_link', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='serp_data_link', to='newsApp.serpdatalink')),
            ],
        ),
    ]
