# Generated by Django 3.1.3 on 2020-11-23 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='newsDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsTitle', models.CharField(max_length=50)),
                ('newsCategory', models.CharField(max_length=30)),
                ('newsDescription', models.CharField(max_length=80)),
                ('newsChannel', models.CharField(max_length=20)),
            ],
        ),
    ]
