# Generated by Django 3.1.3 on 2020-12-08 05:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0003_auto_20201208_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsdetails',
            name='newsDescription',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
