# Generated by Django 3.1.3 on 2020-12-10 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0005_newscategorydescription'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='newsCategoryDescription',
            new_name='newsCategoryList',
        ),
    ]
