# Generated by Django 3.1.3 on 2021-01-14 05:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0005_auto_20210108_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='semrush',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 14, 5, 39, 52, 381346, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='semrush',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
