# Generated by Django 3.1.3 on 2020-12-10 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0006_auto_20201210_1022'),
    ]

    operations = [
        migrations.DeleteModel(
            name='newsCategoryList',
        ),
    ]
