# Generated by Django 3.1.3 on 2021-01-20 06:51

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0006_auto_20210114_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semrush',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 20, 6, 51, 40, 431052, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='SerpDataLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('links', models.TextField(null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2021, 1, 20, 6, 51, 40, 432051, tzinfo=utc))),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('keyword_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serp_semrush', to='newsApp.semrush')),
            ],
        ),
    ]
