# Generated by Django 3.1.3 on 2020-12-10 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0007_delete_newscategorylist'),
    ]

    operations = [
        migrations.CreateModel(
            name='newsCategoryList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsCategoryTitle', models.CharField(max_length=98)),
            ],
        ),
    ]
