# Generated by Django 3.1.3 on 2020-12-10 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0008_newscategorylist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='newsCategoryList',
        ),
    ]
